dist: trusty
matrix:
  include:
    - language: ruby
      rvm:
        - '2.5.1'
      cache: bundler
      before_script:
        - cd kata-server
      script:
        - bundle install
    - language: node_js
      node_js:
        - '10'
      cache:
        directories:
          - node_modules
      before_script:
        - cd kata-frontend
        - yarn install
        - yarn run build
      script:
        - yarn run test
